[project]
name = "translator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alibabacloud-alimt20181012>=1.4.0",
    "python-dotenv>=1.0.1",
    "tencentcloud-sdk-python-tmt>=3.0.1335",
    "volcengine>=1.0.174",
]
